import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'next-i18next';

import { IndexLayout } from '@/components/layout/IndexLayout';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const { locale } = useRouter();
  const [t] = useTranslation('layout');

  return (
    <>
      <Head>
        <title>test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexLayout>
        <h1>{t('Editor')}</h1>
      </IndexLayout>
    </>
  );
};

export default Home;
